disable pix2pix pipelines
fails with ```
RuntimeError: Failed to import transformers.models.blip.processing_blip because of the following error (look up to see its traceback):
[Errno 2] No such file or directory: 'C:\\Users\\Sup\\AppData\\Local\\Temp\\_MEI103522\\transformers\\__init__.py'
[10916] Failed to execute script 'index' due to unhandled exception!
```